# RBAC Admin Server 配置文件示例
# 此文件包含示例配置，请复制为 settings.yaml 并根据实际情况修改

# 服务器配置
server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 15
  write_timeout: 15
  idle_timeout: 60
  max_header_bytes: 1048576

# 数据库配置
# ⚠️ 生产环境请修改以下敏感信息
database:
  type: "mysql"  # 支持: mysql, postgres, sqlite
  host: "localhost"
  port: 3306
  username: "your_username"  # 请修改为您的数据库用户名
  password: "your_password"  # 请修改为您的数据库密码
  database: "rbac_admin"
  charset: "utf8mb4"
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 300

# JWT配置
jwt:
  secret: "your_jwt_secret_key_here"  # ⚠️ 请修改为强密钥
  expire_hours: 24
  issuer: "rbac-admin-server"
  refresh_expire_hours: 168

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: "your_redis_password"  # 如有密码请修改
  db: 0
  max_retries: 3
  pool_size: 10
  min_idle_conns: 5

# 安全配置
security:
  bcrypt_cost: 10
  enable_rate_limit: true
  rate_limit_requests: 100
  rate_limit_window: 60
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  cors_max_age: 86400

# 日志配置
logging:
  level: "info"  # 可选: debug, info, warn, error
  format: "json"  # 可选: json, text
  output: "console"  # 可选: console, file
  file_path: "./logs/app.log"
  max_size: 100  # MB
  max_backups: 3
  max_age: 28  # days

# 应用配置
app:
  name: "RBAC Admin Server"
  version: "1.0.0"
  environment: "development"
  debug: false

# 监控配置
monitoring:
  enable_metrics: true
  metrics_path: "/metrics"
  enable_health_check: true
  health_check_path: "/health"
  enable_tracing: false

# Swagger配置
swagger:
  enabled: true
  host: "localhost:8080"
  base_path: "/api/v1"
  schemes:
    - "http"
    - "https"

# 文件上传配置
upload:
  max_file_size: 10485760  # 10MB
  allowed_types:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "application/pdf"
  upload_dir: "./uploads"

# 性能配置
performance:
  max_connections: 100
  read_buffer_size: 4096
  write_buffer_size: 4096
  rate_limit: 1000
  enable_gzip: true